export { default as Home } from "./Home"
export { default as Leaderboard } from "./Leaderboard"
export { default as Profile } from "./Profile/"
export { default as Signup } from "./Signup"
export { default as Login } from "./Login"
export { default as NotFound } from "./NotFound"
